version: "3"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
