version: '3'
services:
  app:
    container_name: backend
    build: ./projekt_ZTI
    ports:
      - 8088:8088
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
S